-- Use an admin role
USE ROLE ACCOUNTADMIN;
-- Create the `transform` role
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;
-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
PASSWORD='dbtPassword123'
LOGIN_NAME='dbt'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='COMPUTE_WH'
DEFAULT_ROLE='transform'
DEFAULT_NAMESPACE='CAZY.RAW'
COMMENT='DBT user used for data transformation';
GRANT ROLE transform to USER dbt;
-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS CAZY;
CREATE SCHEMA IF NOT EXISTS CAZY.RAW;
-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE transform;
GRANT ALL ON DATABASE CAZY to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE CAZY to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE CAZY to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA CAZY.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA CAZY.RAW to ROLE transform;